server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: spring-feign

  thymeleaf: content-type=text/html
#thymeleaf:
#  encoding: UTF-8
#  servlet:
#    content-type: text/html
